wandb_version: 1

batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 100
num_workers:
  desc: null
  value: 2
cuda:
  desc: null
  value: 0
learning_rate:
  desc: null
  value: 0.0003
weight_decay:
  desc: null
  value: 0.001
seed:
  desc: null
  value: 3407
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1727414981
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 17
      - 23
      - 37
      4: 3.10.14
      5: 0.17.9
      8:
      - 4
      - 5
      10:
      - 3
      13: darwin-arm64
